# Generated by Django 4.1.7 on 2023-03-06 18:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_remove_book_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="gender",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="idiom",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 3, 6, 18, 54, 1, 784668, tzinfo=datetime.timezone.utc
                ),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="published_at",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
    ]
