# Generated by Django 4.1.7 on 2023-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_gender_book_idiom_book_published_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="idiom",
            new_name="languages",
        ),
        migrations.RemoveField(
            model_name="book",
            name="gender",
        ),
        migrations.AddField(
            model_name="book",
            name="genders",
            field=models.ManyToManyField(related_name="books", to="books.gender"),
        ),
    ]
