# Generated by Django 4.1.7 on 2023-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_gender_rename_idiom_book_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender",
            name="name",
            field=models.CharField(
                error_messages={"unique": "This gender is already registered"},
                max_length=150,
                unique=True,
            ),
        ),
    ]
