# Generated by Django 4.1.7 on 2023-03-08 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0008_rename_languages_book_language"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Folower",
            new_name="Follower",
        ),
        migrations.RemoveField(
            model_name="book",
            name="folowers",
        ),
        migrations.AddField(
            model_name="book",
            name="followers",
            field=models.ManyToManyField(
                related_name="books",
                through="books.Follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
