# Generated by Django 4.1.7 on 2023-03-08 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_rename_folower_follower_remove_book_folowers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="user_id",
            new_name="user",
        ),
    ]
