# Generated by Django 4.1.7 on 2023-03-09 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="copy_id",
            new_name="copy",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="user_id",
            new_name="user",
        ),
    ]
