# Generated by Django 4.1.7 on 2023-03-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0003_rename_copy_id_loan_copy_rename_user_id_loan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
