# Generated by Django 4.1.7 on 2023-03-11 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0004_alter_loan_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="borrowed_to_users",
            field=models.ManyToManyField(
                related_name="copies",
                through="copies.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
